apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: nginx-image-updates-image-repo
  namespace: flux-system
spec:
  image: ghcr.io/devops-magazine/nginx
  interval: 1m0s
  secretRef:
    name: regcred
