apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-image-updates
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-image-updates
  template:
    metadata:
      labels:
        app: nginx-image-updates
    spec:
      containers:
      - name: nginx
        image: ghcr.io/devops-magazine/nginx:5.0.0 # {"$imagepolicy": "flux-system:nginx-image-updates-image-policy"}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
