apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: nginx-image-updates-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-image-updates-image-repo
  policy:
    semver:
      range: 5.0.x
